# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(null=True)),
                ('icon', models.URLField()),
                ('rating', models.FloatField()),
                ('review_count', models.CharField(max_length=20)),
                ('current_version', models.CharField(max_length=20)),
                ('supported_os', models.CharField(max_length=20)),
                ('total_downloads', models.CharField(max_length=30)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='appsearch.App')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='appsearch.Developer'),
        ),
    ]
